config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  
  get "/dashboard" => "accounts#index"
  get "profile/:username" => "accounts#profile", as: :profile
  get "post/like/:post_id" => "likes#save_like", as: :like_post
  post "follow/account" =>  "accounts#follow_account", as: :follow_account

  get "follower" => "accounts#follower"
  get "following" => "accounts#following"

  root to: "public#homepage"

  resources :posts, only: [:new, :create, :show]
  resources :comments, only: [:create]
  


end

app/models/account.rb
class Account < ApplicationRecord
  has_many :posts, dependent:   :destroy
  has_many :likes

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,  :trackable

  mount_uploader :image, ImageUploader


  def full_name
  	"#{first_name} #{last_name}"	
  end

  def total_followers
  	Follower.where(follower_id: self.id).count
    
  end

  def total_following
  	Follower.where(following_id: self.id).count
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :post
  belongs_to :account

  validates_presence_of :comment
  validates_presence_of :account_id
  validates_presence_of :post_id

  attr_accessor :return_to

  after_create :increase_post_comment_counter
  after_destroy :decrease_post_comment_counter


	private

	def increase_post_comment_counter
		Post.find(self.post_id).increment(:total_comments_count).save	
	end

	def decrease_post_comment_counter
		Post.find(self.post_id).decrement(:total_comments_count).save	
	end

end

app/models/follower.rb
class Follower < ApplicationRecord
  #belongs_to :accounts
  validates_uniqueness_of :follower_id, scope: :following_id
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :post
	belongs_to :account

	validates_uniqueness_of :post_id, scope: :account_id

	after_create :increase_post_like_counter
	after_destroy :decrease_post_like_counter


	private

	def increase_post_like_counter
		Post.find(self.post_id).increment(:total_likes_count).save	
	end

	def decrease_post_like_counter
		Post.find(self.post_id).decrement(:total_likes_count).save	
	end


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :account
  has_many :likes
  has_many :comments

  default_scope -> { order(created_at: :desc) }
  mount_uploader :image, ImageUploader

  before_create :set_active

  scope :active, ->  { where active: true}

	

  private

  def set_active
  	self.active = true
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	before_action :authenticate_account!
	before_action :set_account, only: [:profile]


	def index

		follower_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
		follower_ids << current_account.id
		@post = Post.includes(:account).where(account_id: follower_ids).active
		@comment = Comment.new

		following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)

		following_ids << current_account.id


		@follower_suggestions = Account.where.not(id: following_ids)
	end

	def profile
		@post = @account.posts.active
	end

	def follow_account

		follower_id = params[:follow_id]
		if Follower.create!(follower_id: current_account.id, following_id: follower_id)
			flash[:success] = "Now Following user"
		else
			flash[:danger] = "Unable to add follower"
		end	
		redirect_to dashboard_path
	end

	def follower
	end

	def follower
	end

	private
	
	def set_account
		@account = Account.find_by_username(params[:username])
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :email, :password, :image, :image_cache, :description, :website])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name, :email, :password])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base

	before_action :authenticate_account!

	

	def create
		@comment = Comment.new(comment_params)
		@comment.account_id = current_account.id if account_signed_in?

		if @comment.save
			return_url = params[:comment][:return_to].present? ? post_path(@comment.post.id) : dashboard_path
			redirect_to return_url, flash: { success: "Comment was created successfully"}
		else
			redirect_to dashboard_path, flash: { success: "Comment was not created"}
		end
	end

	private

		def comment_params
			params.require(:comment).permit(:comment, :post_id, :return_to)
		end 

end

app/controllers/likes_controller.rb
class LikesController < ActionController::Base

  before_action :authenticate_account!

  def save_like
    @like = Like.new(post_id: params[:post_id], account_id: current_account.id )
    @post_id = params[:post_id]
    


    existing_like = Like.where(post_id: @post_id, account_id: current_account.id)
    
    respond_to do |format|
      format.js {
        if existing_like.any?
          existing_like.first.destroy
          @success = false
        elsif @like.save 
             
             @success = true 
        else
            @success = false   
        end 

        @post_likes = Post.find(@post_id).total_likes_count

        render "posts/like"    
        } 
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ActionController::Base

	before_action :authenticate_account!
	before_action :set_post, only: [:show]

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.account_id = current_account.id if account_signed_in?

		if @post.save
			
			redirect_to dashboard_path, flash: { success: "Post was created"}
		else
			redirect_to new_post_path, flash: { success: "Post was not created"}
		end
	end

	def show
		@comment = Comment.new

	end

	def set_post
		@post = Post.find(params[:id]) if params[:id].present?

	end

	private

		def post_params
			params.require(:post).permit(:description,:image, :image_cache)
		end 

end

app/controllers/public_controller.rb
class PublicController < ApplicationController

	def homepage
		
	end
end

app/helpers/accounts_helper.rb
module AccountsHelper
	attr_accessor :friend_request
	def profile_picture account, width = 100 , height = 100
		image_path = account.image.present? ? account.image.url : "user-alt-512.webp"
		image_tag(image_path, width: width , height: height,:class =>  "profile_image")
	end

	def can_edit_profile? profile_id
		account_signed_in? && current_account.id == profile_id

	end
	def get_follower(account_id)
		name= []
		@follower_id=Follower.where(following_id:account_id)
   		@follower_id.each do |f|
      		name<<Account.find_by(id:f.follower_id).full_name()
     	 end
     	 
     	 name.join('<br><br><hr> ').html_safe
     	 
   	end

   	def get_following(account_id)
		name= []
		@following_id=Follower.where(follower_id:account_id)
   		@following_id.each do |f|
      		name<<Account.find_by(id:f.following_id).full_name()
     	 end
     	 
     	 name.join('<br><br><hr> ').html_safe
     	 
   	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def post_liked_by_user? post_id
		Like.where(post_id: post_id, account_id: current_account.id).any?
	end
	
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/accounts/_follower_suggestions.html.erb
<% @follower_suggestions.each do |account| %>
	<div class="recommended-follower">
		<div class="row">
			<div class="col-md-2">
				<%= link_to profile_picture(account, 50, 50), profile_path(account.username) %>
			</div>

			<div class="col-md-10">
				<%= link_to account.username, profile_path(account.username),:class => "text-dar" %><br>
				<p class="text-muted"><%= account.created_at > 2.days.ago ? "New to Friendbook" : "followed by x user" %></p>
				<%= form_tag follow_account_path, method: :post %>
					<%= hidden_field_tag :follow_id, account.id %>
					<%= submit_tag "Add Friend", :class => "btn btn-info btn-sm" %>
			</div>
		</div>
		<br>
	</div>
<% end %>

app/views/accounts/follower.html.erb
<h2 style="text-align: center;">Your Follower</h2>
<div class="container" style="margin-top: 5%">
<div class="row">
	<div class="col-md-5">

	</div>
	<div class="col-md-4">
		<div class="account-summary">
			<p>
				<%= image_tag current_account.image.thumb.url if current_account.image.thumb.url.present? %> 
				<strong><%= link_to current_account.username, profile_path(current_account.username) %></strong>
				<br>
				
			</p>	
		</div>
		<hr>	

		<%= get_follower(current_account)%>
	</div>

</div>
</div>

app/views/accounts/following.html.erb
<div class="container">
<div class="row">
	<div class="col-md-5">

	</div>
	<div class="col-md-4">
		<div class="account-summary">
			<p>
				<%= image_tag current_account.image.thumb.url if current_account.image.thumb.url.present? %> 
				<strong><%= link_to current_account.username, profile_path(current_account.username) %></strong>
				<br>
				
			</p>	
		</div>
		<hr>	

		<%= get_following(current_account)%>
	</div>

</div>
</div>

app/views/accounts/index.html.erb
<div class="container">
	<div class="row ">

		<div class="col-md-8">
			<% @post.each do |post| %>
				<div class="insta-post">
					<div class="post-meta ">
						<% if post.account.image.thumb.url %>
						  <%= image_tag post.account.image.thumb.url, width: "40px", height: "40px",:class =>  "profile_image" %>
						<% else %>
						<%= image_tag "user-alt-512.webp", width: "40px", height: "40px",:class =>  "profile_image" %>
					<% end %>
						<%= link_to post.account.username, profile_path(post.account.username),:class => "text-dar" %>
					
						
         <div style="margin-top: 2% ">
         	<div>
         			<%= simple_format post.description %>
         	</div>
					<%= image_tag post.image.url , width: "100%", height: "400px" %>
				</div>
      </div>
         

			<div class="post-details">
				<div class="post-actions">
          <i class= "fa fa-thumbs-up like-<%= post.id %> <%= 'active' if post_liked_by_user?(post.id) %> fa-2x post-like" data-id="<%= post.id %>" aria-hidden="true"></i>

          <%= link_to post_path(post.id)  do %>
          	<i class="fa fa-comment fa-2x  post-comment"></i> 
          <% end %>  

          <i><p class="text-muted" style=" float: right;"><%= time_ago_in_words post.created_at %> ago</p></i> 
        </div>
        
				<p><strong style="margin-left: 15px;" id="post-<%= post.id %>-likes"><%= post.total_likes_count %>  Likes</strong></p>
				<p><strong id="post-<%= post.id %>-comments"><%= link_to post.account.username, profile_path(post.account.username),:class => "text-dar" %></strong></p>
				<%= render "posts/comments", post: post %>
			</div>

			
			<div class="comment-box">
				<%= form_for @comment do |f| %>

					<%= f.hidden_field :post_id, value: post.id %>
					<div class="input-group-append">
							<%= f.text_field :comment, placeholder: "Add comment here......", :class => "form-control post-comment" %>
						<div class="input-group-append">
							<%= f.submit "Post", class: "btn btn-success float-right" %>
						</div>
					</div>

				<% end %>
			</div>

		</div>	
	<% end %>
</div>

		<div class="col-md-4">
			<div class="account-summary">
				<p>
					<%= image_tag current_account.image.thumb.url if current_account.image.thumb.url.present? %> 
					<strong><%= link_to current_account.username, profile_path(current_account.username) %></strong>
					<br>
					<%= current_account.full_name %>
				</p>	
			</div>

			<div class="follower-suggestions">
				<%= link_to "View All", "#", :class => "float-right" %>
				<p class="text-muted"><strong>Suggestion For You</strong></p>
				<%= render "accounts/follower_suggestions" %>
				
			</div>
		</div>
</div>
	

app/views/accounts/profile.html.erb
<div class="container">
	<div class="row">

		<div class="col-md-4">	
			<div class="img-responsive">
				<%= profile_picture @account, 200, 200 %>
   			</div>
		</div>

		<div class="col-md-8">
			<div class="row">
				<div class="col-md-6" style="float: left;">
					<h2><%= @account.full_name %></h2>
				</div>	
				<div class="col-md-2" style="padding-top: 20px">
					<%= link_to "Edit Profile", edit_account_registration_path, :class => "btn btn-default" if can_edit_profile?(@account.id) %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-4">
			
		</div>
		<div class="col-md-8">
			<div class="col-md-2"><%= @account.posts.count %> posts</div>
			<div class="col-md-2"><%= link_to "Follower", follower_path %></div>
			<div class="col-md-2"><%= link_to "Following", following_path %></div>		
			
			
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-4">
			
		</div>
		<div class="col-md-8">
			<p><%= @account.username %></p>
				<%= simple_format @account.description %>
			<p><%= link_to @account.website if @account.website.present? %></p>
		</div>
	</div>
	</div>
	<hr>

	<div class="container">
		<div class="row">
			<% @post.each do |post| %>
					

			<div class="col-md-3"  style="margin-top: 20px;margin-left: 20px;">
				
						<%= link_to image_tag(post.image.url, width: "100%", height: "250px"), post_path(post) %>
			</div>
			<% end %>
		</div>
	</div>

app/views/layouts/_account_nav.html.erb
<li class="nav-item">
  <%= link_to "Dashboard", dashboard_path, :class => "nav-link"  %>
</li>
<li class="nav-item">
  <%= link_to "New Post", new_post_path, :class => "nav-link"  %> 
</li>
<li class="nav-item">
  <%= link_to "My Profile",profile_path(current_account.username), :class => "nav-link"  %>  
</li>
<li class="nav-item">
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, :class => "nav-link"  %> 
</li> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <title>Friends Book</title>
        
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        
    </head>

  <body>
    <% if account_signed_in? %>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>  
          </button>
          <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Friend's Book</a> 
        </div>  
        <div class="collapse navbar-collapse"id="myNavbar">
          <ul class="nav navbar-nav">
              <%= render "layouts/account_nav" %>
          </ul>
        </div>
      </div>
    </nav>
  <% end %> 

  <!--   page content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-left">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>        
      </div>
    </div>
    
  </div>



    
  </body>
</html>

app/views/posts/_comments.html.erb
<% post.comments.each do |comment| %>
	<div class="comments">
		<%= link_to profile_picture(comment.account ,25 ,25), profile_path(comment.account.username)  %>
		<strong><%= link_to comment.account.username, profile_path(comment.account.username) , class: "text-dark" %></strong>
		<%= comment.comment %>
		<p class=""text-muted><%= time_ago_in_words comment.created_at %> ago</p>
	</div>

<% end %>

app/views/posts/_form.html.erb
<div class="container">
<%= form_for @post, html: { multipart: true} do |f| %>
    
  <div class="form-group">
    <%= f.label :Image %><br/>
    <%= f.file_field :image , :class => "form-control"%>
    <%= f.hidden_field :image_cache , :class => "form-control" %>
  </div>

  <br/>

  <div class="form-group">
    <%= f.label :Description %><br/>
    <%= f.text_area :description, :class => "form-control" %>
  </div>

    <%= f.submit "Save Post", :class => "btn btn-success" %>
<% end %>
</div>

app/views/posts/like.js.erb
<% if @success == true %>
$(".like-<%= @post_id %>").addClass("active");
<% else %>
$(".like-<%= @post_id %>").removeClass("active");
<% end %>
$("#post-<%= @post_id %>-likes").text("<%= @post_likes %> likes");

app/views/posts/new.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
 <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>  
          </button>
          <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Friend's Book</a> 
        </div>  
        <div class="collapse navbar-collapse"id="myNavbar">
          <ul class="nav navbar-nav">
              <%= render "layouts/account_nav" %>
          </ul>
        </div>
      </div>
    </nav>
<div class="container">
<h2>New Post</h2>

<%= render "form" %>
</div>

app/views/posts/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>  
          </button>
          <a class="navbar-brand" href="<%= account_signed_in? ? dashboard_path : root_path %>">Friend's Book</a> 
        </div>  
        <div class="collapse navbar-collapse"id="myNavbar">
          <ul class="nav navbar-nav">
              <%= render "layouts/account_nav" %>
          </ul>
        </div>
      </div>
    </nav>
<div class="container" style="margin-top: 50px"> 
	<div class="row">
		<div class="col-md-2">
			
		</div>
		<div class="col-md-4">
			<div class="comment-post">
				<%= image_tag @post.image.url, width: "100%", height: "50%" if @post.image.present? %>	
	        </div>	
		</div>

		<div class="col-md-4">
			<div class="account-summary">
				<div class="post-meta ">
					<% if @post.account.image.thumb.url %>
					  <%= image_tag @post.account.image.thumb.url, width: "40px", height: "40px",:class =>  "profile_image" %>
					<% else %>
						<%= image_tag "user-alt-512.webp", width: "40px", height: "40px",:class =>  "profile_image" %>
					<% end %>
						<%= link_to @post.account.username, profile_path(@post.account.username),:class => "text-dar" %>
				</div>
			</div>

			<div class="follower-suggestions">
				<div class="post-details">
					<div class="comments-feed" style="height: 200px; overflow: scroll;">
						<%= simple_format @post.description %>
						<%= render "posts/comments", post: @post %>
				  	</div>
				  	<div class="post-actions">
				        <i class="fa fa-thumbs-up like-<%= @post.id %> <%='active' if post_liked_by_user?(@post.id) %> fa-4x post-like" data-id="<%= @post.id %>"></i>
				     
				        <i class="fa fa-commenting fa-2x post-comment"  id="post-comment"></i> 
			        </div>
					<p><strong style="margin-left: 15px;" id="post-<%= @post.id %>-likes"><%= @post.total_likes_count %>  Likes</strong></p>
					<p class=""text-muted><%= time_ago_in_words @post.created_at %> ago</p>
				</div>
			</div>
			<div class="comment-box">
				<%= form_for @comment do |f| %>
					<%= f.hidden_field :post_id, value: @post.id %>
					<%= f.hidden_field :return_to, value: "post" %>
					<div class="col-md-10">
						<div class="input-group-append">
							<%= f.text_field :comment, placeholder: "Add comment here......", :class => "form-control post-comment" %>
						</div>	
					</div>
					<div class="col-md-2">
						<div class="input-group-append">
							<%= f.submit "Post", class: "btn btn-success float-right" %>	
						</div>	
					</div>	
					
					
				<% end %>
			</div>
		</div>
	</div>
</div>
	